version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - ${RBTMQAMQP_PORT}:${RBTMQAMQP_PORT}
      - ${RBTMQHTTP_PORT}:${RBTMQHTTP_PORT}
      - ${RBTMQ_PORT}:${RBTMQ_PORT}
    volumes:
      - ${RBTMQ_CONFIG_DIR}/rabbitmq.conf:/var/lib/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_CONFIG_FILE=/var/lib/rabbitmq/rabbitmq.conf
    networks:
      - satellite
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${RBTMQ_PORT}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  satellite-base:
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    user: "satellite:satellite"
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:${RBTMQAMQP_PORT}
    volumes:
      - ../../logs:/var/log/
      - ./celeryapp:/opt/services/satellite/celeryapp

  satellite-weather:
    hostname: weather
    extends:
      service: satellite-base
    command: /beat_weather.sh
    depends_on:
      - rabbitmq
    restart: always
    healthcheck:
      test: ["CMD-SHELL", 'celery --app satellite_celeryapp.weather.beat.app inspect ping -d "celery@$${HOSTNAME}"']
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

  satellite-downloader:
    hostname: downloader
    extends:
      service: satellite-base
    volumes:
      - ${COPERNICUS_DATA}:/home/satellite/copernicus_data
    command: /beat_downloader.sh
    depends_on:
      - rabbitmq
    restart: always
    healthcheck:
      test: ["CMD-SHELL", 'celery --app satellite_celeryapp.downloader.beat.app inspect ping -d "celery@$${HOSTNAME}"']
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

  flower:
    image: mher/flower
    environment: 
        - CELERY_BROKER_URL=amqp://${RBTMQ_USER}:${RBTMQ_PASSWORD}@rabbitmq:${RBTMQAMQP_PORT}
        - FLOWER_PORT=5555
    networks:
      - satellite
    ports:
        - 5555:5555
    depends_on:
      - rabbitmq
      - satellite-weather
      - satellite-downloader

networks:
  satellite:
      driver: bridge
