version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
    networks:
      - satellite
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  worker:
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
        # ENV: ${ENV}
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_PORT=${PSQL_PORT}
    networks:
      - satellite
    volumes:
      - ../../logs:/var/log/
    depends_on:
      - rabbitmq
    restart: always
    healthcheck:
      test: ["CMD-SHELL", 'celery --app satellite_weather_downloader.celeryapp.app inspect ping -d "celery@$${HOSTNAME}"']
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  satellite:
      driver: bridge
