name: env-satellite
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.11.*
  - docker-compose
  - make
  - celery
  # - satellite-weather-downloader
  - pip
    - git+https://github.com/luabida/satellite-weather-downloader.git@xarray-refactor
