name: tests

on: [push, pull_request]

jobs:
  build:
    environment: env-satellite
    env:
      CDSAPI_KEY: "{{ secrets.API_UUID }}:{{ secrets.API_KEY }}"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ["3.10"]
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 20.11.0
   
    - name: Semantic Release PR Title Check
      uses: osl-incubator/semantic-release-pr-title-check@v1.4.2
      with:                                   
        convention-name: conventionalcommits 

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/dev.yaml
        channels: conda-forge,nodefaults
        activate-environment: env-satellite
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Install dependencies
      run: |
        pip install "cython<3.0.0" 
        pip install --no-build-isolation "pyyaml<6.0"
        poetry install

    - name: Lint
      run: |
        pre-commit run --all-files

    - name: Run tests
      run: |
        pytest -s tests/
