name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: env-satellite
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ["3.10"]
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    
    - name: Semantic Release PR Title Check
      uses: osl-incubator/semantic-release-pr-title-check@v1.0.0

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/dev.yaml
        channels: conda-forge,nodefaults
        activate-environment: env-satellite
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Create env file
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
        API_UUID: ${{ secrets.API_UUID }}
        API_KEY: ${{ secrets.API_KEY }}
        COPER_DATA_DIR_HOST: /home/runner/work/satellite-weather-downloader/data
        COPER_DATA_DIR_CONT: /opt/services/satellite/data
        RBTMQHTTP_PORT: 14672
        RBTMQAMQP_PORT: 5672
        RBTMQ_USER: guest
        RBTMQ_PASSWORD: guest
        RBTMQ_CONFIG_DIR: /home/runner/work/satellite-weather-downloader/docker/rabbitmq/
      run: envsubst < env.tpl > .env

    - name: Build docker images
      run: |
         make docker-build

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Docker start satellite
      run: |
        make docker-start SERVICES="weather downloader" 
